### ISSUE TITLE
The title of the toc should say "Table of Contents"

### ISSUE THREAD

**Issue by rhyek** [terrylinooo/githuber-md#175]
The title of the toc should say "Table of Contents" as plural. Where can I change that?

I tried changing `languages/wp-githuber-md.pot` to have:
```
msgid "Table of Content"
msgstr "Table of Contents"
```

I cleared my cache, it remains the same.

Currenty using this css hack:

```css
.post-toc-block .post-toc-header:after {
  content: 's'
}
```
