### ISSUE TITLE
增加一个灯箱效果，实现Mermaid svg点击放大

### ISSUE THREAD

**Issue by XIGUAjuice** [terrylinooo/githuber-md#268]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

使用mermaid绘制的图像过于复杂时，渲染出的svg字体太小
![image](https://user-images.githubusercontent.com/43206983/150471723-3f66f935-30e2-4868-af23-128ab77f597f.png)

**如何重現**

請告知重現此問題的步驟回何：

1. 使用以下代码块绘制
```mermaid
stateDiagram-v2
[*] --> Still
Still --> [*]
Still --> Moving
Moving --> Still
Moving --> Crash
Crash --> [*]
```

**預期的行為或結果**

实现效果：点击svg使得svg能够全屏渲染，再次点击恢复，如下图
![image](https://user-images.githubusercontent.com/43206983/150472066-39fe634b-e2d6-41db-872b-63d6950417f6.png)

**伺服器環境**

 - WordPress 版本    --5.8.3
 - WP Githuber MD 版本    --1.16.1
 - PHP 版本    --7.4

**用戶端環境**

 - 作業系統    --windows10
 - 瀏覽器    --Edge

**其它說明**

我写了一小段代码，简单地实现了这个功能，由于我水平不够，希望作者能加以改进。

```javascript
$("pre code svg").on("click", function(e) {
	if (e.target !== this) return;
	$(this).toggleClass("code-block-fullscreen");
	$("html").toggleClass("code-block-fullscreen-html-scroll");
})
```

```css
.code-block-fullscreen {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    min-width: 100%;
    z-index: 9999999;
    margin: 0;
    background: white;
    animation: elastic 1s
}

.code-block-fullscreen code {
    --widthA: 100%;
    --widthB: calc(var(--widthA) - 30px);
    height: var(--widthB);
    min-height: 99%;
    overflow-y: hidden;
    overflow-x: auto;
    height: auto
}
})
```
